sudo: required
services:
  - docker

before_install:
  - docker build -t maw488/docker-react -f Dockerfile.dev . 

script:
  - docker run maw488/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "dockaer-react"
  env: "DockaerReact-env"
  bucket_name: elasticbeanstalk-us-west-2-277661746169
  bucket_path: "dockaer-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
